Kufar3/Models/DeclarationTypes.cs
namespace Kufar3.Models
{
    public enum DeclarationTypes
    {
        Active,
        OnModeration,
        Rejected
    }
}

Kufar3/Controllers/DeclarationController.cs
using Kufar3.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kufar3.Helpers;
using Kufar3.ModelsView;
using Kufar3.Repositories;
using Microsoft.AspNet.Identity;

namespace Kufar3.Controllers
{
    public class DeclarationController : BaseController
    {
        [HttpGet]
        public ActionResult AddDeclaration()
        {
            InitDropDownItems();
            ViewBag.Directory = DirectoryTypes.Home;

            return View();
        }

        [HttpPost]
        public ActionResult AddDeclaration( DeclarationModel declaration)
        {
            ViewBag.Directory = DirectoryTypes.Home;
            InitDropDownItems(CategoryRepository.GetCategoryIdBySubCategoryId(declaration.SubCategoryId), RegionRepository.GetRegionIdByCityyId(declaration.CityId));
            if (ModelState.IsValid)
            {
                var newDeclaration = new Declaration
                {
                    Name = declaration.NameD,
                    Description = declaration.Description,
                    SubCategoryId = declaration.SubCategoryId,
                    Type = DeclarationTypes.OnModeration,
                    UserId = UserId,
                    CityId = declaration.CityId,
                };

                DeclarationRepository.Add(newDeclaration);

                foreach (var img in declaration.Images)
                {
                    if (!string.IsNullOrEmpty(img))
                    {
                        ImageRepository.Add(new Image
                        {
                            Name = img,
                            DeclarationId = newDeclaration.Id,
                        });
                    }
                }
                return RedirectToAction("Index", "Home");
            }

            return View(declaration);
        }

        [HttpPost]
        public JsonResult UploadImage(List<HttpPostedFileBase> file)
        {
            System.Threading.Thread.Sleep(2000);

            var k = 0;

            var imag = new List<string>();
            if (file != null)
            {
                foreach (var f in file)
                {
                    if (f != null)
                    {
                        k++;
                        var random = Guid.NewGuid().ToString("n");
                        // получаем имя файла
                        var fileName = "IMG" + random + "-Num" + k + ".jpg";
                        // сохраняем файл в папку Files в проекте
                        f.SaveAs(Server.MapPath("~/Images/" + fileName));
                        var img = "/Images/" + fileName;
                        imag.Add(img);
                    }
                }
            }

            return Json(imag);
        }

        public JsonResult DeleteImage(string url)
        {
            FilesHelper.DeleteImage(url);

            return Json("Удалено", JsonRequestBehavior.AllowGet);
        }
    }
}

Kufar3/Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kufar3.Filters;
using Kufar3.Models;
using Microsoft.SqlServer.Server;
using Microsoft.AspNet.Identity;

namespace Kufar3.Controllers
{
    [MyAuthorize]
    public class PersonalController : BaseController
    {
        public PersonalController()
        {
            ViewBag.Directory = DirectoryTypes.PersonalDeclarations;
        }

        public ActionResult MyDeclarations(DeclarationTypes declarationType = DeclarationTypes.Active, int page = 1)
        {
            var query = DeclarationRepository.GetDeclarationsByUserId(UserId);
            int pageSize = 5;   // количество элементов на странице 
            ViewBag.ActiveCount = query.Count(x => x.Type == DeclarationTypes.Active);
            ViewBag.ModerationCount = query.Count(x => x.Type == DeclarationTypes.OnModeration);
            ViewBag.RejectedCount = query.Count(x => x.Type == DeclarationTypes.Rejected);

            switch (declarationType)
            {
                case DeclarationTypes.Active:
                    query = query.Where(x => x.Type == DeclarationTypes.Active);
                    break;
                case DeclarationTypes.OnModeration:
                    query = query.Where(x => x.Type == DeclarationTypes.OnModeration);
                    break;
                case DeclarationTypes.Rejected:
                    query = query.Where(x => x.Type == DeclarationTypes.Rejected);
                    break;
            }

            var count = query.Count();

            var items = query
                .OrderBy(x => x.CreatedDate)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.DeclarationType = declarationType;
            ViewBag.PageSize = pageSize;
            ViewBag.CurrentPage = page;
            ViewBag.Count = count;
            ViewBag.Declarations = items;

            return View();
        }

        [HttpGet]
        public ActionResult UserDeclaration(long? declarationId)
        {
            var declaration = DeclarationRepository.GetById(declarationId);
            ViewBag.Declaration = declaration;
            

            var countEmptyImages = 6 - declaration.Images.Count;
            for (var i = 0; i < countEmptyImages; i++)
            {
                declaration.Images.Add(new Image
                {
                    Name = "/ContentImages/null.jpg",
                    DeclarationId = declaration.Id,
                });
            }
            InitDropDownItems(declaration.SubCategory.CategoryId, declaration.City.RegionId);

            return View(declaration);
        }

        [HttpPost]
        public ActionResult DeclarationUpdate(Declaration declaration)
        {
            DeclarationRepository.Update(declaration);

            return RedirectToAction("MyDeclarations");
        }

        public ActionResult DeleteDeclaration(int? declarationId)
        {
            DeclarationRepository.Remove(declarationId);

            return RedirectToAction("MyDeclarations");
        }
        /********************************************************************************************************/

        public ActionResult AccountEdit()
        {
            var model = UserRepository.GetById(UserId);
            ViewBag.Directory = DirectoryTypes.PersonalSettings;
            ViewBag.Avatar = UserRepository.GetAvatar(UserId);

            return View(model);
        }

        [HttpPost]
        public ActionResult AccountEdit(User model, HttpPostedFileBase file)
        {
            if (file != null)
            {
                UserRepository.Edit(model, file);
            }
            
            ViewBag.Directory = DirectoryTypes.PersonalSettings;
            ViewBag.Avatar = UserRepository.GetAvatar(UserId);

            return View();
        }
    }
}

Kufar3/Views/Declaration/AddDeclaration.cshtml
@model Kufar3.ModelsView.DeclarationModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var categories = (SelectList) ViewBag.Categories;
    var subCategories = (SelectList) ViewBag.SubCategories;
    var regions = (SelectList) ViewBag.Regions;
    var cities = (SelectList) ViewBag.Cities;
}
<div class="content">
    <h2>Выберите изображения</h2>

    <div id="all-images">
        @for (var i = 1; i < 7; i++)
        {
            <div class="image" id="img-@i">
                <button>X</button>
                <img/>
            </div>
        }
    </div>

    <input hidden class="file-input-hidden" type="file" id="files" name="files" multiple/>

    @using (Html.BeginForm("AddDeclaration", "Declaration", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.Images[0], new {id = "formId0"})
        @Html.HiddenFor(x => x.Images[1], new {id = "formId1"})
        @Html.HiddenFor(x => x.Images[2], new {id = "formId2"})
        @Html.HiddenFor(x => x.Images[3], new {id = "formId3"})
        @Html.HiddenFor(x => x.Images[4], new {id = "formId4"})
        @Html.HiddenFor(x => x.Images[5], new {id = "formId5"})
        <br/>
        <table>
            <tr>
                <td>
                    <p>Раздел:</p>
                </td>
                <td>@Html.DropDownList("Category", categories, new {id = "Category"})</td>
            </tr>
            <tr>
                <td>
                    <p>Подраздел:</p>
                </td>
                <td>@Html.DropDownListFor(x => x.SubCategoryId, subCategories, new {id = "SubCategoryId"})</td>
            </tr>
            <tr>
                <td>
                    <p>Область:</p>
                </td>
                <td>@Html.DropDownList("Region", regions, new {id = "Region"})</td>
            </tr>
            <tr>
                <td>
                    <p>Город:</p>
                </td>
                <td>@Html.DropDownListFor(x => x.CityId, cities, new {id = "CityId"})</td>
            </tr>
            <tr>
                <td>
                    <p>Название:</p>
                </td>
                <td>
                    @Html.TextBoxFor(x => x.NameD)
                    @Html.ValidationMessageFor(x => x.NameD)
                </td>
            </tr>
            <tr>
                <td>
                    <p>Описание:</p>
                </td>
                <td>@Html.TextAreaFor(x => x.Description, new {style = "height: 80px; width: 350px; font-size:12px; "})
                    @Html.ValidationMessageFor(x => x.Description)
                </td>
            </tr>
            <tr>
            <tr>
                <td>
                    <input type="submit" value="Отправить"/>
                </td>
            </tr>
        </table>
    }
</div>

<script type="text/javascript">
    $(function()
    {
        $('#Category').change(function()
        {
            // получаем выбранный id
            var id = $(this).val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetItems", "Home")/' + id,
                success: function(data)
                {
                    console.log("vernulll", data);
                    // заменяем содержимое присланным частичным представлением
                    $('#SubCategoryId').replaceWith(data);
                }
            });
        });
    });

    $(function()
    {
        $('#Region').change(function()
        {
            // получаем выбранный id
            var id = $(this).val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetCities", "Home")/' + id,
                success: function(data)
                {
                    console.log("vernulllCity", data);
                    // заменяем содержимое присланным частичным представлением
                    $('#CityId').replaceWith(data);
                }
            });
        });
    });
</script>

Kufar3/Views/Declaration/DeclarationShow.cshtml
@using Kufar3.Models

@{
    var declarations = (List<Declaration>) ViewBag.Declarations;
    var userRole = (UserRoles) ViewBag.UserRole;
    var userId = (int) ViewBag.UserId;
    var directory = (DirectoryTypes) ViewBag.Directory;
}

<ul>
    @foreach (var declaration in declarations)
    {
        <li class="declarations">
            @if (declaration.UserId == userId && directory == DirectoryTypes.PersonalDeclarations)
            {
                <div id="menu-desc">
                    <b>@Html.ActionLink("Изменить", "UserDeclaration", "Personal", new {declarationId = declaration.Id}, null) </b>
                    <b>@Html.ActionLink("Удалить", "DeleteDeclaration", "Personal", new {declarationId = declaration.Id}, null)</b>

                </div>
            }
            @{
                var path = declaration.Images.FirstOrDefault()?.Name;
                var url = Url.Action("Declaration", "Home", new {declarationId = declaration.Id});

                if (userRole == UserRoles.Moderator && directory == DirectoryTypes.Moderator)
                {
                    url = Url.Action("DeclarationModeration", "Moderator", new {declarationId = declaration.Id});
                }
            }

            <div class="img">
                <a href="@url">
                    <img src="@path" alt="No img"/>
                </a>
            </div>
            <div class="desc">
                <p class="nameD">
                    <b>
                        <a href="@url">@declaration.Name</a>
                    </b>
                </p>
                @*<br/>*@
                <div class="text">
                    @declaration.CreatedDate / @declaration.City.Region.Name / @declaration.City.Name<br/>
                    @declaration.SubCategory.Category.Name / @declaration.SubCategory.Name
                    <div class="price"> @declaration.Price p.</div>
                </div>

            </div>
        </li>
    }
</ul>

<div id="pagination"></div>

<script>
    var declarationType = '@ViewBag.DeclarationType';
    var pageSize = Number('@ViewBag.PageSize');
    var currentPage = Number('@ViewBag.CurrentPage');
    var countDeclaration = Number('@ViewBag.Count');
    var idCategory = Number('@TempData["idCategory"]');
    var idSubcategory = Number('@TempData["idSubCategory"]');
</script>

@{
    switch (directory)
    {
        case DirectoryTypes.Home:
            <script>
                new Pagination(Pagination.urlHome);
            </script>
            break;
        case DirectoryTypes.PersonalDeclarations:
            <script>
                new Pagination(Pagination.urlPersonal);
            </script>
            break;
        case DirectoryTypes.Moderator:
            <script>
                new Pagination(Pagination.urlModerator);
            </script>
            break;
        case DirectoryTypes.PersonalSettings:
            break;
    }
}

Kufar3/Views/Declaration/DeclarationView.cshtml
@using Kufar3.Models
@model Kufar3.Models.Declaration
@{
    string region = Model.City.Region.Name;
    string category = Model.SubCategory.Category.Name;
    var userId = (int)ViewBag.UserId;
    var directory = (DirectoryTypes)ViewBag.Directory;
}
@if (Model.UserId == userId && directory == DirectoryTypes.PersonalDeclarations)
{
    <div class="user-menu">
        <b>@Html.ActionLink("Удалить", "DeleteDeclaration", "Personal", new { declarationId = Model.Id }, null)</b>
        <b>@Html.ActionLink("Изменить", "UserDeclaration", "Personal", new { declarationId = Model.Id }, null) </b>
    </div>
}

<div class="all-elements">
    <div class="foto">
        <img src="../../ContentImages/chevron-sign-left.svg" id="left-button">
        <img src="../../ContentImages/right-arrowhead-in-a-circle.svg" id="right-button">
        <img src="@Model.Images.First().Name" alt="No img" id="declaration-img" />
    </div>
    <div class="contacts">
        <b class="price-decl">Цена: @Model.Price р.</b><br /><br />
        <b>@Model.Name</b><br /><br />
        
        Контактное лицо:&nbsp;@Model.User.Name <br />
        Телефон:&nbsp;@Model.User.MobileNumber<br />
        <br />
        Область:&nbsp;@region <br />
        Город:&nbsp;@Model.City.Name <br /><br />
    </div>
    <div class="all-foto">
        @foreach (var image in Model.Images)
        {
            var path = image.Name;
            <img src="@path" alt="No img" />
        }
    </div>
</div>
   
<div id="description">
    <br />
    <b>Категория:&nbsp;</b>@category <br />
    <b>Подкатегория:&nbsp;</b>@Model.SubCategory.Name
    <br /><br />
    <b>Цена:&nbsp;</b><b class="price-decl">@Model.Price р.</b><br />
    <br />
    <b>Описание:&nbsp;</b>@Model.Description <br />
</div>
<br />


<script type="text/javascript">
    $(function () {
        var i = 0;
        var array = $('.all-foto img');

        $('#right-button').click(function () {
            if (i < array.length - 1)
                i++;
            if (i < array.length) {
                button();
            }
        });

        $('#left-button').click(function () {
            if (i > 0)
                i--;
            if (i >= 0) {
                button();
            }
        });

        $('.all-foto img').click(function () {
            i = $('.all-foto img').index(this);
            button();
        });

        function button() {
            var elem = $(array[i]).attr('src');
            $('#declaration-img').attr('src', elem);
            $(`.all-foto img`).removeClass('img-light');
            $(`.all-foto img:eq(${i})`).addClass('img-light');
        };
    });
</script>